In [34]:
import csv

with open('teste.txt') as csvfile:
        #Tomo a prerrogativa de que o arquivo .txt possui um formato step válido
    
        # Propriedades de Interesse
        retStrName = ''
        retNumTot = 0
        retPeFirst = ''
        retPeLast = ''
   
        #Abre o arquivo e coleta informações
        spamreader = csv.reader(csvfile, delimiter=':', quotechar='|')
        numLinha= 0
        
        for row in spamreader:
            print(row)
            numLinha+= 1
            lenRow = len(row)
            if numLinha== 1:
                retStrName = row[0]
            else:
                if lenRow >= 4:
                    retNumTot += int(row[0])
                    retPeLast = row[3]
                    if numLinha == 2:
                        retPeFirst = row[3]
                    
                    
    
    
        print('Nome = ' + retStrName)
        print('Total = ' + str(retNumTot))
        print('Primeiro = ' + retPeFirst)
        print('Ultimo = ' + retPeLast)

['DNC_Zouk_V1_Condutor_BAS_LAT_DIR']
['1', '2', '3', 'pD.ABR']
['2', '1', '1', 'pE.JCF']
['3', '1', '2', 'pD.LUG']
Nome = DNC_Zouk_V1_Condutor_BAS_LAT_DIR
Total = 6
Primeiro = pD.ABR
Ultimo = pD.LUG

In [1]:
import criarDBTemp as ct

In [8]:
a,l = ct.tbSTP_updateOrNewChildFromNo(20,'FRT','leaf','')

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 20
    And tbSTP.strNAME = 'FRT'
    And tbSTP.strTYPE = 'leaf'
    Order By tbSTP.codNo

In [19]:
a['codNO'].values[0]

21

In [14]:
b,l = ct.tbSTP_updateOrNewChildFromNo(25,'TOTAL','prop','')

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 25
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo

In [20]:
l

0

In [2]:
ct.mostrar()

tbNO:
    typeNO  codPointer  drwGX  drwGY  drwLev  drwHei  drwPos drwRel  booActive
cod
1     root           0     -1     -1      -1      -1      -1                 1
2      stp           1     -1     -1      -1      -1      -1                 1
3      stp           2     -1     -1      -1      -1      -1                 1
4      stp           3     -1     -1      -1      -1      -1                 1
5      stp           4     -1     -1      -1      -1      -1                 1
6      stp           5     -1     -1      -1      -1      -1                 1
7      stp           6     -1     -1      -1      -1      -1                 1
8      stp           7     -1     -1      -1      -1      -1                 1
9      stp           8     -1     -1      -1      -1      -1                 1
10     stp           9     -1     -1      -1      -1      -1                 1
11     stp          10     -1     -1      -1      -1      -1                 1
12     stp          11     -1     -1      -1      -1      -1                 1
13     stp          12     -1     -1      -1      -1      -1                 1
14     stp          13     -1     -1      -1      -1      -1                 1
15     stp          14     -1     -1      -1      -1      -1                 1
16     stp          15     -1     -1      -1      -1      -1                 1
17     stp          16     -1     -1      -1      -1      -1                 1
18     stp          17     -1     -1      -1      -1      -1                 1
19     stp          18     -1     -1      -1      -1      -1                 1
20     stp          19     -1     -1      -1      -1      -1                 1
21     stp          20     -1     -1      -1      -1      -1                 1
22     stp          21     -1     -1      -1      -1      -1                 1
23     stp          22     -1     -1      -1      -1      -1                 1
24     stp          23     -1     -1      -1      -1      -1                 1
25     stp          24     -1     -1      -1      -1      -1                 1
tbAD:
       typeAD  codFrom  codTo
cod
1    root-mod        1      2
2     mod-sub        2      3
3    sub-cond        3      4
4    cond-tag        4      5
5     tag-tag        5      6
6    tag-leaf        6      7
7    tag-leaf        6      8
8     tag-tag        5      9
9    tag-leaf        9     10
10   tag-leaf        9     11
11    tag-tag        5     12
12   tag-leaf       12     13
13   tag-leaf       12     14
14   sub-cond        3     15
15   cond-tag       15     16
16    tag-tag       16     17
17   tag-leaf       17     18
18   tag-leaf       17     19
19    tag-tag       16     20
20   tag-leaf       20     21
21   tag-leaf       20     22
22    tag-tag       16     23
23   tag-leaf       23     24
24   tag-leaf       23     25
tbSTP:
       strNAME strTYPE strVALUE  codNO
cod
0          STP    root               1
1         Zouk     mod               2
2           V1     sub               3
3     Condutor    cond               4
4          BAS     tag               5
5          LAT     tag               6
6          ESQ    leaf               7
7          DIR    leaf               8
8          VER     tag               9
9          FRT    leaf              10
10         TRS    leaf              11
11         LUG     tag              12
12         ESQ    leaf              13
13         DIR    leaf              14
14   Conduzido    cond              15
15         BAS     tag              16
16         LAT     tag              17
17         ESQ    leaf              18
18         DIR    leaf              19
19         VER     tag              20
20         FRT    leaf              21
21         TRS    leaf              22
22         LUG     tag              23
23         ESQ    leaf              24
24         DIR    leaf              25

In [4]:
ct.tbSTP_updateValueByCodNO(25,'')

In [6]:
ct.mostrar()

tbNO:
    typeNO  codPointer  drwGX  drwGY  drwLev  drwHei  drwPos drwRel  booActive
cod
1     root           0     -1     -1      -1      -1      -1                 1
2      stp           1     -1     -1      -1      -1      -1                 1
3      stp           2     -1     -1      -1      -1      -1                 1
4      stp           3     -1     -1      -1      -1      -1                 1
5      stp           4     -1     -1      -1      -1      -1                 1
6      stp           5     -1     -1      -1      -1      -1                 1
7      stp           6     -1     -1      -1      -1      -1                 1
8      stp           7     -1     -1      -1      -1      -1                 1
9      stp           8     -1     -1      -1      -1      -1                 1
10     stp           9     -1     -1      -1      -1      -1                 1
11     stp          10     -1     -1      -1      -1      -1                 1
12     stp          11     -1     -1      -1      -1      -1                 1
13     stp          12     -1     -1      -1      -1      -1                 1
14     stp          13     -1     -1      -1      -1      -1                 1
15     stp          14     -1     -1      -1      -1      -1                 1
16     stp          15     -1     -1      -1      -1      -1                 1
17     stp          16     -1     -1      -1      -1      -1                 1
18     stp          17     -1     -1      -1      -1      -1                 1
19     stp          18     -1     -1      -1      -1      -1                 1
20     stp          19     -1     -1      -1      -1      -1                 1
21     stp          20     -1     -1      -1      -1      -1                 1
22     stp          21     -1     -1      -1      -1      -1                 1
23     stp          22     -1     -1      -1      -1      -1                 1
24     stp          23     -1     -1      -1      -1      -1                 1
25     stp          24     -1     -1      -1      -1      -1                 1
tbAD:
       typeAD  codFrom  codTo
cod
1    root-mod        1      2
2     mod-sub        2      3
3    sub-cond        3      4
4    cond-tag        4      5
5     tag-tag        5      6
6    tag-leaf        6      7
7    tag-leaf        6      8
8     tag-tag        5      9
9    tag-leaf        9     10
10   tag-leaf        9     11
11    tag-tag        5     12
12   tag-leaf       12     13
13   tag-leaf       12     14
14   sub-cond        3     15
15   cond-tag       15     16
16    tag-tag       16     17
17   tag-leaf       17     18
18   tag-leaf       17     19
19    tag-tag       16     20
20   tag-leaf       20     21
21   tag-leaf       20     22
22    tag-tag       16     23
23   tag-leaf       23     24
24   tag-leaf       23     25
tbSTP:
       strNAME strTYPE strVALUE  codNO
cod
0          STP    root               1
1         Zouk     mod               2
2           V1     sub               3
3     Condutor    cond               4
4          BAS     tag               5
5          LAT     tag               6
6          ESQ    leaf               7
7          DIR    leaf               8
8          VER     tag               9
9          FRT    leaf              10
10         TRS    leaf              11
11         LUG     tag              12
12         ESQ    leaf              13
13         DIR    leaf              14
14   Conduzido    cond              15
15         BAS     tag              16
16         LAT     tag              17
17         ESQ    leaf              18
18         DIR    leaf              19
19         VER     tag              20
20         FRT    leaf              21
21         TRS    leaf              22
22         LUG     tag              23
23         ESQ    leaf              24
24         DIR    leaf              25

In [3]:
ct.verificaLeafs()

#########
codNo 7:STP_Zouk_V1_Condutor_BAS_LAT_ESQ existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Condutor_BAS_LAT_ESQ Total: 6 First:pE.ABR Last:pE.LUG

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 7
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 7
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 7
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 7
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 8:STP_Zouk_V1_Condutor_BAS_LAT_DIR existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Condutor_BAS_LAT_DIR Total: 6 First:pD.ABR Last:pD.LUG

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 8
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 8
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 8
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 8
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 10:STP_Zouk_V1_Condutor_BAS_VER_FRT existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Condutor_BAS_VER_FRT Total: 6 First:pD.FRT Last:pD.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 10
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 10
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 10
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 10
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 11:STP_Zouk_V1_Condutor_BAS_VER_TRS existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Condutor_BAS_VER_TRS Total: 6 First:pE.TRS Last:pE.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 11
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 11
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 11
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 11
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 13:STP_Zouk_V1_Condutor_BAS_LUG_ESQ existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Condutor_BAS_LUG_ESQ Total: 6 First:pE.JUN Last:pE.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 13
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 13
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 13
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 13
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 14:STP_Zouk_V1_Condutor_BAS_LUG_DIR existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Condutor_BAS_LUG_DIR Total: 6 First:pD.JUN Last:pD.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 14
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 14
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 14
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 14
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 18:STP_Zouk_V1_Conduzido_BAS_LAT_ESQ existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Conduzido_BAS_LAT_ESQ Total: 6 First:pD.ACF Last:pD.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 18
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 18
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 18
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 18
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 19:STP_Zouk_V1_Conduzido_BAS_LAT_DIR existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Conduzido_BAS_LAT_DIR Total: 6 First:pE.ACF Last:pE.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 19
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 19
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 19
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 19
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 21:STP_Zouk_V1_Conduzido_BAS_VER_FRT existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Conduzido_BAS_VER_FRT Total: 6 First:pD.FRT Last:pD.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 21
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 21
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 21
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 21
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 22:STP_Zouk_V1_Conduzido_BAS_VER_TRS existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Conduzido_BAS_VER_TRZ Total: 6 First:pE.TRS Last:pE.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 22
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 22
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 22
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 22
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 24:STP_Zouk_V1_Conduzido_BAS_LUG_ESQ existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Conduzido_BAS_LUG_ESQ Total: 6 First:pE.JUN Last:pE.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 24
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 24
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 24
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 24
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


#########
codNo 25:STP_Zouk_V1_Conduzido_BAS_LUG_DIR existe! Coletando atributos
##########

Nome: DNC_Zouk_V1_Conduzido_BAS_LUG_DIR Total: 6 First:pD.JUN Last:pD.JUN

    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 25
    And tbSTP.strNAME = 'NAME'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 25
    And tbSTP.strNAME = 'TOTAL'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 25
    And tbSTP.strNAME = 'FIRST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo


    Select
    tbAD.cod as cod,
    tbAD.typeAD as typeAD,
    tbAD.codFrom as codFrom,
    tbAD.codTo as codTo,
    tbSTP.cod as codSTP,
    tbSTP.strNAME as strNAME,
    tbSTP.strTYPE as strTYPE,
    tbSTP.strVALUE as strVALUE,
    tbSTP.codNO as codNO
    From tbAD, tbSTP
    Where tbAD.cod > 0
    And tbAD.codTo = tbSTP.codNO
    And tbAD.codFrom = 25
    And tbSTP.strNAME = 'LAST'
    And tbSTP.strTYPE = 'prop'
    Order By tbSTP.codNo

    strNAME strTYPE strVALUE  codNO
cod
6       ESQ    leaf               7
7       DIR    leaf               8
9       FRT    leaf              10
10      TRS    leaf              11
12      ESQ    leaf              13
13      DIR    leaf              14
17      ESQ    leaf              18
18      DIR    leaf              19
20      FRT    leaf              21
21      TRS    leaf              22
23      ESQ    leaf              24
24      DIR    leaf              25

In [4]:
ct.mostrar()

tbNO:
    typeNO  codPointer  drwGX  drwGY  drwLev  drwHei  drwPos drwRel  booActive
cod
1     root           0     -1     -1      -1      -1      -1                 1
2      stp           1     -1     -1      -1      -1      -1                 1
3      stp           2     -1     -1      -1      -1      -1                 1
4      stp           3     -1     -1      -1      -1      -1                 1
5      stp           4     -1     -1      -1      -1      -1                 1
6      stp           5     -1     -1      -1      -1      -1                 1
7      stp           6     -1     -1      -1      -1      -1                 1
8      stp           7     -1     -1      -1      -1      -1                 1
9      stp           8     -1     -1      -1      -1      -1                 1
10     stp           9     -1     -1      -1      -1      -1                 1
11     stp          10     -1     -1      -1      -1      -1                 1
12     stp          11     -1     -1      -1      -1      -1                 1
13     stp          12     -1     -1      -1      -1      -1                 1
14     stp          13     -1     -1      -1      -1      -1                 1
15     stp          14     -1     -1      -1      -1      -1                 1
16     stp          15     -1     -1      -1      -1      -1                 1
17     stp          16     -1     -1      -1      -1      -1                 1
18     stp          17     -1     -1      -1      -1      -1                 1
19     stp          18     -1     -1      -1      -1      -1                 1
20     stp          19     -1     -1      -1      -1      -1                 1
21     stp          20     -1     -1      -1      -1      -1                 1
22     stp          21     -1     -1      -1      -1      -1                 1
23     stp          22     -1     -1      -1      -1      -1                 1
24     stp          23     -1     -1      -1      -1      -1                 1
25     stp          24     -1     -1      -1      -1      -1                 1
26     stp          25     -1     -1      -1      -1      -1                 1
27     stp          26     -1     -1      -1      -1      -1                 1
28     stp          27     -1     -1      -1      -1      -1                 1
29     stp          28     -1     -1      -1      -1      -1                 1
30     stp          29     -1     -1      -1      -1      -1                 1
..     ...         ...    ...    ...     ...     ...     ...    ...        ...
44     stp          43     -1     -1      -1      -1      -1                 1
45     stp          44     -1     -1      -1      -1      -1                 1
46     stp          45     -1     -1      -1      -1      -1                 1
47     stp          46     -1     -1      -1      -1      -1                 1
48     stp          47     -1     -1      -1      -1      -1                 1
49     stp          48     -1     -1      -1      -1      -1                 1
50     stp          49     -1     -1      -1      -1      -1                 1
51     stp          50     -1     -1      -1      -1      -1                 1
52     stp          51     -1     -1      -1      -1      -1                 1
53     stp          52     -1     -1      -1      -1      -1                 1
54     stp          53     -1     -1      -1      -1      -1                 1
55     stp          54     -1     -1      -1      -1      -1                 1
56     stp          55     -1     -1      -1      -1      -1                 1
57     stp          56     -1     -1      -1      -1      -1                 1
58     stp          57     -1     -1      -1      -1      -1                 1
59     stp          58     -1     -1      -1      -1      -1                 1
60     stp          59     -1     -1      -1      -1      -1                 1
61     stp          60     -1     -1      -1      -1      -1                 1
62     stp          61     -1     -1      -1      -1      -1                 1
63     stp          62     -1     -1      -1      -1      -1                 1
64     stp          63     -1     -1      -1      -1      -1                 1
65     stp          64     -1     -1      -1      -1      -1                 1
66     stp          65     -1     -1      -1      -1      -1                 1
67     stp          66     -1     -1      -1      -1      -1                 1
68     stp          67     -1     -1      -1      -1      -1                 1
69     stp          68     -1     -1      -1      -1      -1                 1
70     stp          69     -1     -1      -1      -1      -1                 1
71     stp          70     -1     -1      -1      -1      -1                 1
72     stp          71     -1     -1      -1      -1      -1                 1
73     stp          72     -1     -1      -1      -1      -1                 1

[73 rows x 9 columns]
tbAD:
        typeAD  codFrom  codTo
cod
1     root-mod        1      2
2      mod-sub        2      3
3     sub-cond        3      4
4     cond-tag        4      5
5      tag-tag        5      6
6     tag-leaf        6      7
7     tag-leaf        6      8
8      tag-tag        5      9
9     tag-leaf        9     10
10    tag-leaf        9     11
11     tag-tag        5     12
12    tag-leaf       12     13
13    tag-leaf       12     14
14    sub-cond        3     15
15    cond-tag       15     16
16     tag-tag       16     17
17    tag-leaf       17     18
18    tag-leaf       17     19
19     tag-tag       16     20
20    tag-leaf       20     21
21    tag-leaf       20     22
22     tag-tag       16     23
23    tag-leaf       23     24
24    tag-leaf       23     25
25   leaf-prop        7     26
26   leaf-prop        7     27
27   leaf-prop        7     28
28   leaf-prop        7     29
29   leaf-prop        8     30
30   leaf-prop        8     31
..         ...      ...    ...
43   leaf-prop       13     44
44   leaf-prop       13     45
45   leaf-prop       14     46
46   leaf-prop       14     47
47   leaf-prop       14     48
48   leaf-prop       14     49
49   leaf-prop       18     50
50   leaf-prop       18     51
51   leaf-prop       18     52
52   leaf-prop       18     53
53   leaf-prop       19     54
54   leaf-prop       19     55
55   leaf-prop       19     56
56   leaf-prop       19     57
57   leaf-prop       21     58
58   leaf-prop       21     59
59   leaf-prop       21     60
60   leaf-prop       21     61
61   leaf-prop       22     62
62   leaf-prop       22     63
63   leaf-prop       22     64
64   leaf-prop       22     65
65   leaf-prop       24     66
66   leaf-prop       24     67
67   leaf-prop       24     68
68   leaf-prop       24     69
69   leaf-prop       25     70
70   leaf-prop       25     71
71   leaf-prop       25     72
72   leaf-prop       25     73

[72 rows x 3 columns]
tbSTP:
       strNAME strTYPE                           strVALUE  codNO
cod
0          STP    root                                         1
1         Zouk     mod                                         2
2           V1     sub                                         3
3     Condutor    cond                                         4
4          BAS     tag                                         5
5          LAT     tag                                         6
6          ESQ    leaf                                         7
7          DIR    leaf                                         8
8          VER     tag                                         9
9          FRT    leaf                                        10
10         TRS    leaf                                        11
11         LUG     tag                                        12
12         ESQ    leaf                                        13
13         DIR    leaf                                        14
14   Conduzido    cond                                        15
15         BAS     tag                                        16
16         LAT     tag                                        17
17         ESQ    leaf                                        18
18         DIR    leaf                                        19
19         VER     tag                                        20
20         FRT    leaf                                        21
21         TRS    leaf                                        22
22         LUG     tag                                        23
23         ESQ    leaf                                        24
24         DIR    leaf                                        25
25        NAME    prop   DNC_Zouk_V1_Condutor_BAS_LAT_ESQ     26
26       TOTAL    prop                                  6     27
27       FIRST    prop                             pE.ABR     28
28        LAST    prop                             pE.LUG     29
29        NAME    prop   DNC_Zouk_V1_Condutor_BAS_LAT_DIR     30
..         ...     ...                                ...    ...
43       FIRST    prop                             pE.JUN     44
44        LAST    prop                             pE.JUN     45
45        NAME    prop   DNC_Zouk_V1_Condutor_BAS_LUG_DIR     46
46       TOTAL    prop                                  6     47
47       FIRST    prop                             pD.JUN     48
48        LAST    prop                             pD.JUN     49
49        NAME    prop  DNC_Zouk_V1_Conduzido_BAS_LAT_ESQ     50
50       TOTAL    prop                                  6     51
51       FIRST    prop                             pD.ACF     52
52        LAST    prop                             pD.JUN     53
53        NAME    prop  DNC_Zouk_V1_Conduzido_BAS_LAT_DIR     54
54       TOTAL    prop                                  6     55
55       FIRST    prop                             pE.ACF     56
56        LAST    prop                             pE.JUN     57
57        NAME    prop  DNC_Zouk_V1_Conduzido_BAS_VER_FRT     58
58       TOTAL    prop                                  6     59
59       FIRST    prop                             pD.FRT     60
60        LAST    prop                             pD.JUN     61
61        NAME    prop  DNC_Zouk_V1_Conduzido_BAS_VER_TRZ     62
62       TOTAL    prop                                  6     63
63       FIRST    prop                             pE.TRS     64
64        LAST    prop                             pE.JUN     65
65        NAME    prop  DNC_Zouk_V1_Conduzido_BAS_LUG_ESQ     66
66       TOTAL    prop                                  6     67
67       FIRST    prop                             pE.JUN     68
68        LAST    prop                             pE.JUN     69
69        NAME    prop  DNC_Zouk_V1_Conduzido_BAS_LUG_DIR     70
70       TOTAL    prop                                  6     71
71       FIRST    prop                             pD.JUN     72
72        LAST    prop                             pD.JUN     73

[73 rows x 4 columns]